# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-03 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170102_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
